# Generated by Django 3.2.5 on 2022-06-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_creator_id_comment_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.group'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.document'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.group'),
        ),
    ]
