# Generated by Django 3.2.5 on 2022-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20220608_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentuser',
            name='modified_time',
            field=models.DateTimeField(),
        ),
    ]
